name: feature pipeline
# Controls when the workflow will run (Triggers on every code push)
on: [push]

jobs:
  feature-pipeline:   #job name
    if: github.ref_name == 'feature-*'
    uses: vinod1618/workflows/.github/workflows/node-js-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue' 