name: feature pipeline
# Controls when the workflow will run (Triggers on every code push)
on:
  workflow_dispatch:
  #push:
  

jobs:
  feature-pipeline:   #job name
    if: github.ref_name != 'main'
    uses: vinoddevops1618/workflows/.github/workflows/node-js-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'
    secrets: inherit
    permissions:
      contents: read
      statuses: write    # read repo files